services:

  db:
    image: postgres:17
    container_name: adventure-postgres-db
    restart: always
    environment:
      POSTGRES_DB: adventure-game
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - adventure-game-postgres-data:/var/lib/postgresql/data
    networks:
      - adventure-game-network

  frontend:
    build:
      context: ./adventure.client
      dockerfile: Dockerfile
      args:
        VITE_FRONTEND_SUBPATH: "/"
        VITE_BACKEND_API_URL: "http://localhost:8688"
    ports:
      - "8680:80"  # React Ã¼ber Nginx
    environment:
      # api.ts
      VITE_BACKEND_API_URL: "http://localhost:8688"
      # nginx.conf.template, vite.config.ts, main.tsx, docker-entrypoint.sh, vite-env.d.ts
      VITE_FRONTEND_SUBPATH: "/"
    depends_on:
      - backend
    networks:
      - adventure-game-network
      - container_app_network 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventure-game-frontend.entrypoints=websecure"
      - "traefik.http.routers.adventure-game-frontend.rule=Host(`elitegames.v6.rocks`) && PathPrefix(`/adventure-game`)"
      - "traefik.http.routers.adventure-game-frontend.tls.certresolver=letencrypt"
      - "traefik.http.services.adventure-game-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=container_app_network"
  
  backend:
    build:
      context: ./adventure.server
      dockerfile: Dockerfile
    ports:
      - "8688:8080"
    environment:
      #application.properties
      BACKEND_SUBPATH: "/"       
      CORS_CSV_LIST: "http://localhost:8680"
    networks:
      - adventure-game-network
      - container_app_network 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventure-game-backend.entrypoints=websecure"
      - "traefik.http.routers.adventure-game-backend.rule=Host(`elitegames.v6.rocks`) && PathPrefix(`/adventure-game-api`)"
      - "traefik.http.routers.adventure-game-backend.tls.certresolver=letencrypt"
      - "traefik.http.services.adventure-game-backend.loadbalancer.server.port=8080"
      - "traefik.docker.network=container_app_network"

volumes:
  adventure-game-postgres-data:
  
networks:
  adventure-game-network:
    driver: bridge
  container_app_network:
    external: true