services:

  db:
    image: postgres:17
    container_name: adventure-postgres-db
    restart: always
    environment:
      POSTGRES_DB: adventure-game
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - adventure-game-postgres-data:/var/lib/postgresql/data
    networks:
      - adventure-game-network

  frontend:
    build:
      context: ./adventure.client
      dockerfile: Dockerfile
    ports:
      - "8680:80"  # React Ã¼ber Nginx
    depends_on:
      - backend
    networks:
      - adventure-game-network
      - container_app_network 
  
  backend:
    build:
      context: ./adventure.server
      dockerfile: Dockerfile
    ports:
      - "8688:8080"
    networks:
      - adventure-game-network
      - container_app_network 

volumes:
  adventure-game-postgres-data:
  

networks:
  adventure-game-network:
    driver: bridge
  container_app_network:
    external: true